trigger: none

pool:
  name: 'irfank'

variables:
  BUILD_COMMAND: 'gradlew clean build'
  SSC_URL: 'https://192.168.13.177:8443/ssc/'
  SSC_APP_NAME: 'Gradle'
  SSC_APP_VERSION: 'azure-sca-scan'
  JAVA_HOME_PATH: 'C:\Program Files\Amazon Corretto\jdk21.0.12_9'
  SCANCENTRAL_HOME_PATH: 'C:\Fortify\ScanCentral'

stages:
  - stage: BuildCheck
    displayName: 'Gradle Build Check'
    jobs:
      - job: TestBuild
        steps:
          - checkout: self
            clean: true

          - task: CmdLine@2
            displayName: 'Set Environment'
            inputs:
              script: |
                echo ##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_PATH)
                echo ##vso[task.prependpath]$(JAVA_HOME_PATH)\bin
                echo ##vso[task.prependpath]$(SCANCENTRAL_HOME_PATH)\bin

          - task: CmdLine@2
            displayName: 'Check Java Version'
            inputs:
              script: 'java -version'

          - task: CmdLine@2
            displayName: 'Check Gradle Version'
            inputs:
              script: 'gradlew -v'

          - task: CmdLine@2
            displayName: 'Gradle Build'
            inputs:
              script: '$(BUILD_COMMAND)'

  - stage: RemoteScan
    displayName: 'ScanCentral Remote Scan'
    dependsOn: BuildCheck
    jobs:
      - job: ScanJob
        steps:
          - checkout: self
            clean: true

          - task: CmdLine@2
            displayName: 'Set Environment'
            inputs:
              script: |
                echo ##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_PATH)
                echo ##vso[task.prependpath]$(JAVA_HOME_PATH)\bin
                echo ##vso[task.prependpath]$(SCANCENTRAL_HOME_PATH)\bin

          - task: CmdLine@2
            displayName: 'ScanCentral Remote Scan'
            inputs:
              script: 'scancentral -sscurl "$(SSC_URL)" -ssctoken "$(FortifyAuthToken)" start -bt gradle -bc "clean build" -upload -application "$(SSC_APP_NAME)" -version "$(SSC_APP_VERSION)" -uptoken "$(FortifyAuthToken)"'