
package ejbs;

import javax.ejb.*;

/**
 * Created Aug 31, 2004 4:38:09 PM
 * Code generated by the Sun ONE Studio EJB Builder
 * @author sreeni
 */

public interface SessionHome extends javax.ejb.EJBHome {
    
    public ejbs.Session create()
    throws javax.ejb.CreateException, java.rmi.RemoteException;
    
}
