
package ejbs;

import javax.ejb.*;

/**
 * Created Aug 31, 2004 4:38:09 PM
 * Code generated by the Sun ONE Studio EJB Builder
 * @author sreeni
 */

public interface Session extends javax.ejb.EJBObject {
    
    public void business(String s) throws java.rmi.RemoteException;
    
}

